services:
  # Exposing APIs and file hosting to the internet via Cloudflare
  AIRTV_cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}

  airtvreverseproxy:
    image: nginx:latest
    container_name: airtv-reverse-proxy
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    #depends_on:
    #  - AIRTV_api
    #  - AIRTV_host

  #airtv-api:
  #  image: your_domain_image
  #  container_name: airtv-api
  #  volumes:
  #    - ./conf/host.nginx.conf:/etc/nginx/nginx.conf:ro
  #  ports:
  #    - "8000:8000"

  airtvhost:
    image: nginx:latest
    container_name: airtv_host
    ports:
      - "7000:80"
    volumes:
      - build_volume:/usr/share/nginx/html
    depends_on:
      - airtvbuilder  # Ensure builder starts first

  airtvbuilder:
    build:
      context: .
      dockerfile: buildSite.Dockerfile
      args:
        GITHUB_PAT: ${GITHUB_PAT}
    volumes:
      - build_volume:/build  # Mount the volume at runtime


  airtvhooks:
    build: 
      context: .
      dockerfile: webhookd.Dockerfile
    container_name: airtv-hooks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # If you need to control Docker
      - ./htpasswd:/etc/webhookd/.htpasswd  # Mount the password file
    env_file:
      - .env
    environment:
      - WHD_HOOK_SCRIPTS=/scripts
      - WHD_HOOK_DEFAULT_EXT=.sh
      - WHD_HOOK_DEFAULT_MODE=buffered
      - WHD_HOOK_TIMEOUT=10
      - WHD_PASSWD_FILE=/etc/webhookd/.htpasswd  # Set auth file
      - WHD_LOG_MODULES=hook
      - GITHUB_PAT=${GITHUB_PAT}  # Pass the PAT
    ports:
      - "9000:8080"     # Port where the webhook listens
    restart: unless-stopped

volumes:
  build_volume:

networks:
  default:
    name: airtv-tunnel
